//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("db", "TweetTwitrucUser", "Tweet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Twitruc.DAL.Tweet), "TwitrucUser", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Twitruc.DAL.TwUser))]

#endregion

namespace Twitruc.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbContainer object using the connection string found in the 'dbContainer' section of the application configuration file.
        /// </summary>
        public dbContainer() : base("name=dbContainer", "dbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbContainer object.
        /// </summary>
        public dbContainer(string connectionString) : base(connectionString, "dbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbContainer object.
        /// </summary>
        public dbContainer(EntityConnection connection) : base(connection, "dbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TwUser> UserSet
        {
            get
            {
                if ((_UserSet == null))
                {
                    _UserSet = base.CreateObjectSet<TwUser>("UserSet");
                }
                return _UserSet;
            }
        }
        private ObjectSet<TwUser> _UserSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tweet> TweetSet
        {
            get
            {
                if ((_TweetSet == null))
                {
                    _TweetSet = base.CreateObjectSet<Tweet>("TweetSet");
                }
                return _TweetSet;
            }
        }
        private ObjectSet<Tweet> _TweetSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserSet(TwUser twUser)
        {
            base.AddObject("UserSet", twUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TweetSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTweetSet(Tweet tweet)
        {
            base.AddObject("TweetSet", tweet);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db", Name="Tweet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tweet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tweet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tweetId">Initial value of the TweetId property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="authorNick">Initial value of the AuthorNick property.</param>
        /// <param name="sent">Initial value of the Sent property.</param>
        public static Tweet CreateTweet(global::System.Int64 id, global::System.Int64 tweetId, global::System.String content, global::System.DateTime date, global::System.String authorNick, global::System.Boolean sent)
        {
            Tweet tweet = new Tweet();
            tweet.Id = id;
            tweet.TweetId = tweetId;
            tweet.Content = content;
            tweet.Date = date;
            tweet.AuthorNick = authorNick;
            tweet.Sent = sent;
            return tweet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TweetId
        {
            get
            {
                return _TweetId;
            }
            set
            {
                OnTweetIdChanging(value);
                ReportPropertyChanging("TweetId");
                _TweetId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TweetId");
                OnTweetIdChanged();
            }
        }
        private global::System.Int64 _TweetId;
        partial void OnTweetIdChanging(global::System.Int64 value);
        partial void OnTweetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AuthorNick
        {
            get
            {
                return _AuthorNick;
            }
            set
            {
                OnAuthorNickChanging(value);
                ReportPropertyChanging("AuthorNick");
                _AuthorNick = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AuthorNick");
                OnAuthorNickChanged();
            }
        }
        private global::System.String _AuthorNick;
        partial void OnAuthorNickChanging(global::System.String value);
        partial void OnAuthorNickChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Sent
        {
            get
            {
                return _Sent;
            }
            set
            {
                OnSentChanging(value);
                ReportPropertyChanging("Sent");
                _Sent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sent");
                OnSentChanged();
            }
        }
        private global::System.Boolean _Sent;
        partial void OnSentChanging(global::System.Boolean value);
        partial void OnSentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db", "TweetTwitrucUser", "TwitrucUser")]
        public TwUser TwitrucUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TwUser>("db.TweetTwitrucUser", "TwitrucUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TwUser>("db.TweetTwitrucUser", "TwitrucUser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TwUser> TwitrucUsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TwUser>("db.TweetTwitrucUser", "TwitrucUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TwUser>("db.TweetTwitrucUser", "TwitrucUser", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db", Name="TwUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TwUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TwUser object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="nickname">Initial value of the Nickname property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="token">Initial value of the Token property.</param>
        /// <param name="tokenSecret">Initial value of the TokenSecret property.</param>
        /// <param name="twitterNick">Initial value of the TwitterNick property.</param>
        public static TwUser CreateTwUser(global::System.Int64 id, global::System.String name, global::System.String email, global::System.String nickname, global::System.String password, global::System.String token, global::System.String tokenSecret, global::System.String twitterNick)
        {
            TwUser twUser = new TwUser();
            twUser.Id = id;
            twUser.Name = name;
            twUser.Email = email;
            twUser.Nickname = nickname;
            twUser.Password = password;
            twUser.Token = token;
            twUser.TokenSecret = tokenSecret;
            twUser.TwitterNick = twitterNick;
            return twUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nickname
        {
            get
            {
                return _Nickname;
            }
            set
            {
                OnNicknameChanging(value);
                ReportPropertyChanging("Nickname");
                _Nickname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nickname");
                OnNicknameChanged();
            }
        }
        private global::System.String _Nickname;
        partial void OnNicknameChanging(global::System.String value);
        partial void OnNicknameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Token
        {
            get
            {
                return _Token;
            }
            set
            {
                OnTokenChanging(value);
                ReportPropertyChanging("Token");
                _Token = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Token");
                OnTokenChanged();
            }
        }
        private global::System.String _Token;
        partial void OnTokenChanging(global::System.String value);
        partial void OnTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TokenSecret
        {
            get
            {
                return _TokenSecret;
            }
            set
            {
                OnTokenSecretChanging(value);
                ReportPropertyChanging("TokenSecret");
                _TokenSecret = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TokenSecret");
                OnTokenSecretChanged();
            }
        }
        private global::System.String _TokenSecret;
        partial void OnTokenSecretChanging(global::System.String value);
        partial void OnTokenSecretChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TwitterNick
        {
            get
            {
                return _TwitterNick;
            }
            set
            {
                OnTwitterNickChanging(value);
                ReportPropertyChanging("TwitterNick");
                _TwitterNick = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TwitterNick");
                OnTwitterNickChanged();
            }
        }
        private global::System.String _TwitterNick;
        partial void OnTwitterNickChanging(global::System.String value);
        partial void OnTwitterNickChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db", "TweetTwitrucUser", "Tweet")]
        public EntityCollection<Tweet> Tweet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tweet>("db.TweetTwitrucUser", "Tweet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tweet>("db.TweetTwitrucUser", "Tweet", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
