//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("db", "UserEntity1", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Twitruc.DAL.TwitrucUser), "Tweet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Twitruc.DAL.Tweet))]

#endregion

namespace Twitruc.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbContainer object using the connection string found in the 'dbContainer' section of the application configuration file.
        /// </summary>
        public dbContainer() : base("name=dbContainer", "dbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbContainer object.
        /// </summary>
        public dbContainer(string connectionString) : base(connectionString, "dbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbContainer object.
        /// </summary>
        public dbContainer(EntityConnection connection) : base(connection, "dbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TwitrucUser> TwitrucUsers
        {
            get
            {
                if ((_TwitrucUsers == null))
                {
                    _TwitrucUsers = base.CreateObjectSet<TwitrucUser>("TwitrucUsers");
                }
                return _TwitrucUsers;
            }
        }
        private ObjectSet<TwitrucUser> _TwitrucUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tweet> Tweets
        {
            get
            {
                if ((_Tweets == null))
                {
                    _Tweets = base.CreateObjectSet<Tweet>("Tweets");
                }
                return _Tweets;
            }
        }
        private ObjectSet<Tweet> _Tweets;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TwitrucUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTwitrucUsers(TwitrucUser twitrucUser)
        {
            base.AddObject("TwitrucUsers", twitrucUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tweets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTweets(Tweet tweet)
        {
            base.AddObject("Tweets", tweet);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db", Name="Tweet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tweet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tweet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tweetId">Initial value of the TweetId property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Tweet CreateTweet(global::System.Guid id, global::System.Int64 tweetId, global::System.String content, global::System.DateTime date)
        {
            Tweet tweet = new Tweet();
            tweet.Id = id;
            tweet.TweetId = tweetId;
            tweet.Content = content;
            tweet.Date = date;
            return tweet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TweetId
        {
            get
            {
                return _TweetId;
            }
            set
            {
                OnTweetIdChanging(value);
                ReportPropertyChanging("TweetId");
                _TweetId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TweetId");
                OnTweetIdChanged();
            }
        }
        private global::System.Int64 _TweetId;
        partial void OnTweetIdChanging(global::System.Int64 value);
        partial void OnTweetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db", "UserEntity1", "User")]
        public TwitrucUser User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TwitrucUser>("db.UserEntity1", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TwitrucUser>("db.UserEntity1", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TwitrucUser> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TwitrucUser>("db.UserEntity1", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TwitrucUser>("db.UserEntity1", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db", Name="TwitrucUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TwitrucUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TwitrucUser object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="nickname">Initial value of the Nickname property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="token">Initial value of the Token property.</param>
        /// <param name="tokenSecret">Initial value of the TokenSecret property.</param>
        /// <param name="twitterNick">Initial value of the TwitterNick property.</param>
        /// <param name="inscription">Initial value of the Inscription property.</param>
        public static TwitrucUser CreateTwitrucUser(global::System.Guid id, global::System.String name, global::System.String email, global::System.String nickname, global::System.String password, global::System.String token, global::System.String tokenSecret, global::System.String twitterNick, global::System.DateTime inscription)
        {
            TwitrucUser twitrucUser = new TwitrucUser();
            twitrucUser.Id = id;
            twitrucUser.Name = name;
            twitrucUser.Email = email;
            twitrucUser.Nickname = nickname;
            twitrucUser.Password = password;
            twitrucUser.Token = token;
            twitrucUser.TokenSecret = tokenSecret;
            twitrucUser.TwitterNick = twitterNick;
            twitrucUser.Inscription = inscription;
            return twitrucUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nickname
        {
            get
            {
                return _Nickname;
            }
            set
            {
                OnNicknameChanging(value);
                ReportPropertyChanging("Nickname");
                _Nickname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nickname");
                OnNicknameChanged();
            }
        }
        private global::System.String _Nickname;
        partial void OnNicknameChanging(global::System.String value);
        partial void OnNicknameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Token
        {
            get
            {
                return _Token;
            }
            set
            {
                OnTokenChanging(value);
                ReportPropertyChanging("Token");
                _Token = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Token");
                OnTokenChanged();
            }
        }
        private global::System.String _Token;
        partial void OnTokenChanging(global::System.String value);
        partial void OnTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TokenSecret
        {
            get
            {
                return _TokenSecret;
            }
            set
            {
                OnTokenSecretChanging(value);
                ReportPropertyChanging("TokenSecret");
                _TokenSecret = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TokenSecret");
                OnTokenSecretChanged();
            }
        }
        private global::System.String _TokenSecret;
        partial void OnTokenSecretChanging(global::System.String value);
        partial void OnTokenSecretChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TwitterNick
        {
            get
            {
                return _TwitterNick;
            }
            set
            {
                OnTwitterNickChanging(value);
                ReportPropertyChanging("TwitterNick");
                _TwitterNick = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TwitterNick");
                OnTwitterNickChanged();
            }
        }
        private global::System.String _TwitterNick;
        partial void OnTwitterNickChanging(global::System.String value);
        partial void OnTwitterNickChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Inscription
        {
            get
            {
                return _Inscription;
            }
            set
            {
                OnInscriptionChanging(value);
                ReportPropertyChanging("Inscription");
                _Inscription = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inscription");
                OnInscriptionChanged();
            }
        }
        private global::System.DateTime _Inscription;
        partial void OnInscriptionChanging(global::System.DateTime value);
        partial void OnInscriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db", "UserEntity1", "Tweet")]
        public EntityCollection<Tweet> Entity1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tweet>("db.UserEntity1", "Tweet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tweet>("db.UserEntity1", "Tweet", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
